---
collections:
  - name: amazon.aws
    version: ">=6.0.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.grafana
    version: ">=1.5.0"
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.crypto
    version: ">=2.15.0"
  - name: community.aws
    version: ">=6.0.0"